export const ENV = {
  RPC_URL: process.env.NEXT_PUBLIC_RPC_URL!,
  NETWORK_PASSPHRASE: process.env.NEXT_PUBLIC_NETWORK_PASSPHRASE!,
  WALLET_WASM_HASH: process.env.NEXT_PUBLIC_WALLET_WASM_HASH!,
  LAUNCHTUBE_URL: process.env.NEXT_PUBLIC_LAUNCHTUBE_URL!,
  LAUNCHTUBE_JWT: process.env.NEXT_PUBLIC_LAUNCHTUBE_JWT!,
  MERCURY_PROJECT_NAME: process.env.NEXT_PUBLIC_MERCURY_PROJECT_NAME!,
  MERCURY_URL: process.env.NEXT_PUBLIC_MERCURY_URL!,
  MERCURY_JWT: process.env.NEXT_PUBLIC_MERCURY_JWT!,
  NATIVE_CONTRACT_ID: process.env.NEXT_PUBLIC_NATIVE_CONTRACT_ID!,
  FUNDER_SECRET_KEY: process.env.NEXT_PUBLIC_FUNDER_SECRET_KEY!,
};
